export enum ErrorCode {
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
  INVALID_INPUT = "INVALID_INPUT",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_EXPIRED_TOKEN = "INVALID_EXPIRED_TOKEN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}
